image: node:11.12.0-stretch
  
# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - contract/node_modules/

test:
  script:
   - cd contract
   - npm install
   - npm build
   - npm test

pages:
  stage: deploy
  script: 
    - cd frontend/my-fundraising
    - npm install
    - npm run build --prod --base-href=/e01305257/ --output-path ../../public
  when: always
  artifacts:
    paths:
    - public
  only:
  - master

